/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaswing_crud;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.List;
import java.util.ArrayList;

/**
 *
 * @author DIMAS
 */

// inheritance & encapsulasi
public class CRUDFrame extends javax.swing.JFrame {

    /**
     * Membet new form CRUDFrame
     */
    public CRUDFrame() {
        initComponents();
        try {
            loadData();
            loadDaftarPeminjam();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Memuat Data!", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
        addTableSelectionListener();
        logoutButton.addActionListener(e -> {
            this.dispose(); // tutup CRUDFrame
            LoginFrame login = new LoginFrame();
            login.setVisible(true); // tampilkan form login
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Author = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tahun = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TambahButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Jumlah = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        Daftar_Peminjam = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SetujuiButton = new javax.swing.JButton();
        KembalikanButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ADMIN PERPUS");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 200));

        jLabel1.setText("Nama Buku");

        Nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NamaActionPerformed(evt);
            }
        });

        jLabel2.setText("Author");

        jLabel3.setText("Tahun Terbit");

        jLabel4.setText("Status");

        TambahButton.setBackground(new java.awt.Color(0, 204, 51));
        TambahButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        TambahButton.setForeground(new java.awt.Color(255, 255, 255));
        TambahButton.setText("TAMBAH");
        TambahButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahButtonActionPerformed(evt);
            }
        });

        UpdateButton.setBackground(new java.awt.Color(0, 153, 255));
        UpdateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        UpdateButton.setForeground(new java.awt.Color(255, 255, 255));
        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        HapusButton.setBackground(new java.awt.Color(255, 51, 51));
        HapusButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HapusButton.setForeground(new java.awt.Color(255, 255, 255));
        HapusButton.setText("HAPUS");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TERSEDIA", "RUSAK", "HILANG" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("SISTEM INFORMASI PERPUSTAKAAN");

        Jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JumlahActionPerformed(evt);
            }
        });

        jLabel7.setText("Jumlah Buku");

        logoutButton.setBackground(new java.awt.Color(255, 51, 51));
        logoutButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("LOGOUT");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TambahButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdateButton)
                        .addGap(18, 18, 18)
                        .addComponent(HapusButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Nama)
                            .addComponent(Author, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE))
                        .addGap(80, 80, 80)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Tahun, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Jumlah))
                .addGap(62, 62, 62))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(161, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(109, 109, 109)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Author, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TambahButton)
                            .addComponent(UpdateButton)
                            .addComponent(HapusButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))))
                .addGap(392, 392, 392))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(34, 34, 34)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(514, 514, 514)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Buku", "Author", "Tahun Terbit", "Jumlah Buku", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Daftar_Peminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nama Peminjam", "Nama Buku", "Author", "Tahun", "Status"
            }
        ));
        jScrollPane2.setViewportView(Daftar_Peminjam);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DAFTAR PEMINJAM");

        SetujuiButton.setBackground(new java.awt.Color(0, 204, 51));
        SetujuiButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SetujuiButton.setForeground(new java.awt.Color(255, 255, 255));
        SetujuiButton.setText("SETUJUI");
        SetujuiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SetujuiButtonActionPerformed(evt);
            }
        });

        KembalikanButton.setBackground(new java.awt.Color(255, 51, 51));
        KembalikanButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        KembalikanButton.setForeground(new java.awt.Color(255, 255, 255));
        KembalikanButton.setText("TOLAK");
        KembalikanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembalikanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(116, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(SetujuiButton)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KembalikanButton)
                .addGap(109, 109, 109))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SetujuiButton)
                    .addComponent(KembalikanButton))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void loadData() throws SQLException {
    BukuDAO bukuDAO = new BukuDAO();
    List<Buku> bukuList = bukuDAO.getBuku();
    String[][] data = new String[bukuList.size()][6];

    for (int i = 0; i < bukuList.size(); i++) {
        data[i][0] = String.valueOf(bukuList.get(i).getId());
        data[i][1] = bukuList.get(i).getNama();
        data[i][2] = bukuList.get(i).getAuthor();
        data[i][3] = bukuList.get(i).getTahun();
        data[i][4] = String.valueOf(bukuList.get(i).getJumlah());  // konversi int ke String
        data[i][5] = bukuList.get(i).getStatus();
    }

    String[] columnNames = {"ID", "Nama Buku", "Author", "Tahun Terbit", "Jumlah Buku", "Status"};
    jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));

    // Sembunyikan kolom ID agar tidak terlihat
    jTable1.getColumnModel().getColumn(0).setMinWidth(0);
    jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
    jTable1.getColumnModel().getColumn(0).setWidth(0);
}

    // Tambahkan listener agar data tabel bisa di-load ke form
    private void addTableSelectionListener() {
        jTable1.getSelectionModel().addListSelectionListener(e -> {
            int selectedRow = jTable1.getSelectedRow();
            if (selectedRow != -1) {
                Nama.setText(jTable1.getValueAt(selectedRow, 1).toString());
                Author.setText(jTable1.getValueAt(selectedRow, 2).toString());
                Tahun.setText(jTable1.getValueAt(selectedRow, 3).toString());
                Jumlah.setText(jTable1.getValueAt(selectedRow, 4).toString());
                jComboBox1.setSelectedItem(jTable1.getValueAt(selectedRow, 4).toString());
            }
        });
    }
    
    private void clearForm(){
        Nama.setText("");
        Author.setText("");
        Tahun.setText("");
        Jumlah.setText("");
        jComboBox1.setSelectedIndex(0);
    }
    
    private void loadDaftarPeminjam() throws SQLException {
    BukuDAO bukuDAO = new BukuDAO();
    List<Buku> bukuList = bukuDAO.getBuku();

    // Filter buku yang statusnya DIPINJAM atau PENDING
    List<Buku> dipinjamList = new ArrayList<>();
    for (Buku b : bukuList) {
        String status = b.getStatus().toUpperCase();
        if (status.equals("DIPINJAM") || status.equals("PENDING")) {
            dipinjamList.add(b);
        }
    }

    String[][] data = new String[dipinjamList.size()][5];

    for (int i = 0; i < dipinjamList.size(); i++) {
        Buku b = dipinjamList.get(i);
        data[i][0] = String.valueOf(b.getId());
        data[i][1] = b.getNama();
        data[i][2] = b.getAuthor();
        data[i][3] = b.getTahun();
        data[i][4] = b.getStatus();
    }

    String[] columnNames = {"Nama Peminjam", "Nama Buku", "Author", "Tahun Terbit", "Status"};
    Daftar_Peminjam.setModel(new javax.swing.table.DefaultTableModel(data, columnNames));

    // Jika mau sembunyikan kolom ID bisa seperti ini:
    Daftar_Peminjam.getColumnModel().getColumn(0).setMinWidth(0);
    Daftar_Peminjam.getColumnModel().getColumn(0).setMaxWidth(0);
    Daftar_Peminjam.getColumnModel().getColumn(0).setWidth(0);
}

    private void updateStatusBuku(int idBuku, String newStatus) {
    try {
        java.sql.Connection conn = DBConnection.getConnection();
        java.sql.PreparedStatement ps = conn.prepareStatement(
            "UPDATE buku SET status = ? WHERE id_buku = ?"
        );
        ps.setString(1, newStatus);
        ps.setInt(2, idBuku);
        
        int updated = ps.executeUpdate();
        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "Status buku berhasil diperbarui ke: " + newStatus);
            loadDaftarPeminjam(); // Refresh tabel
        } else {
            JOptionPane.showMessageDialog(this, "Gagal memperbarui status buku.");
        }

        ps.close();
        conn.close();
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
    }
}
 
           
    private void TambahButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahButtonActionPerformed
   String nama = Nama.getText();
   String author = Author.getText();
   String tahun = Tahun.getText();
   String jumlah = Jumlah.getText();
   String status = jComboBox1.getSelectedItem().toString(); // dari ComboBox

   // Validasi input kosong
   if (nama.isEmpty() || author.isEmpty() || tahun.isEmpty() || jumlah.isEmpty() || status.isEmpty()) {
       JOptionPane.showMessageDialog(this, "Tolong isi semua form!", "ERROR", JOptionPane.ERROR_MESSAGE);
       return;
   }

   // Validasi tahun harus angka 4 digit
   if (!tahun.matches("\\d{4}")) {
       JOptionPane.showMessageDialog(this, "Tahun harus berupa angka 4 digit!", "ERROR", JOptionPane.ERROR_MESSAGE);
       return;
   }

   // Validasi jumlah harus angka (misalnya 1, 10, 100, dll.)
   if (!jumlah.matches("\\d+")) {
       JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!", "ERROR", JOptionPane.ERROR_MESSAGE);
       return;
   }

   try {
       int jumlahInt = Integer.parseInt(jumlah);  // parsing jumlah ke int
       Buku buku = new Buku(0, nama, author, tahun, jumlahInt, status);
       BukuDAO bukuDAO = new BukuDAO();
       int result = bukuDAO.insertBuku(buku);

       if (result > 0) {
           JOptionPane.showMessageDialog(this, "Data buku berhasil ditambahkan!");
           clearForm(); // Bersihkan form
           loadData();  // Muat ulang data ke tabel
       } else {
           JOptionPane.showMessageDialog(this, "Gagal menambahkan data buku.");
       }
   } catch (NumberFormatException nfe) {
       JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!", "ERROR", JOptionPane.ERROR_MESSAGE);
   } catch (Exception e) {
       JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
   }
    }//GEN-LAST:event_TambahButtonActionPerformed

    private void NamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NamaActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
    int selectedRow = jTable1.getSelectedRow();

    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih data yang ingin diedit!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
        String nama = Nama.getText();
        String author = Author.getText();
        String tahun = Tahun.getText();
        String jumlah = Jumlah.getText();  // <== Tambahkan ini
        String status = jComboBox1.getSelectedItem().toString();

        // Validasi form tidak kosong
        if (nama.isEmpty() || author.isEmpty() || tahun.isEmpty() || jumlah.isEmpty() || status.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Form tidak boleh kosong!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi tahun 4 digit angka
        if (!tahun.matches("\\d{4}")) {
            JOptionPane.showMessageDialog(this, "Tahun harus berupa angka 4 digit!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validasi jumlah angka positif
        if (!jumlah.matches("\\d+")) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka!", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Buat objek Buku sesuai constructor
        int jumlahInt = Integer.parseInt(jumlah);  // parsing jumlah ke int
        Buku buku = new Buku(id, nama, author, tahun, jumlahInt, status);  // ← fix disini!
        BukuDAO dao = new BukuDAO();
        int result = dao.updateBuku(buku);

        if (result > 0) {
            JOptionPane.showMessageDialog(this, "Data berhasil diupdate!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            loadData();
            clearForm();
        } else {
            JOptionPane.showMessageDialog(this, "Gagal update data!", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan pada database!", "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih data yang ingin dihapus!", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                int id = Integer.parseInt(jTable1.getValueAt(selectedRow, 0).toString());
                BukuDAO dao = new BukuDAO();
                int result = dao.deleteBuku(id);

                if (result > 0) {
                    JOptionPane.showMessageDialog(this, "Data berhasil dihapus!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    loadData();
                    clearForm();
                } else {
                    JOptionPane.showMessageDialog(this, "Gagal menghapus data!", "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan pada database!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void SetujuiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SetujuiButtonActionPerformed
        int row = Daftar_Peminjam.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih buku terlebih dahulu.");
            return;
        }
        int idBuku = Integer.parseInt(Daftar_Peminjam.getModel().getValueAt(row, 0).toString());
        updateStatusBuku(idBuku, "DIPINJAM");
    }//GEN-LAST:event_SetujuiButtonActionPerformed

    private void JumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JumlahActionPerformed

    private void KembalikanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembalikanButtonActionPerformed
        int row = Daftar_Peminjam.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Pilih buku terlebih dahulu.");
            return;
        }
        int idBuku = Integer.parseInt(Daftar_Peminjam.getModel().getValueAt(row, 0).toString());
        updateStatusBuku(idBuku, "TERSEDIA");
    }//GEN-LAST:event_KembalikanButtonActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Author;
    private javax.swing.JTable Daftar_Peminjam;
    private javax.swing.JButton HapusButton;
    private javax.swing.JTextField Jumlah;
    private javax.swing.JButton KembalikanButton;
    private javax.swing.JTextField Nama;
    private javax.swing.JButton SetujuiButton;
    private javax.swing.JTextField Tahun;
    private javax.swing.JButton TambahButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
